### ISSUE TITLE
SyntaxError: 'return' outside function

### ISSUE THREAD

**Issue by crack00r** [bwentzloff/trading-bot#11]
root@j314793:/trading-bot/part 3# python backtest.py
Traceback (most recent call last):
  File "backtest.py", line 4, in <module>
    from botstrategy import BotStrategy
  File "/root/trading-bot/part 3/botstrategy.py", line 2, in <module>
    from botindicators import BotIndicators
  File "/root/trading-bot/part 3/botindicators.py", line 23
    return a
SyntaxError: 'return' outside function
root@j314793:/trading-bot/part 3#

**Comment by Menox10** [comment]
I had the same problem. The error is in the EMA and MACD functions. When you comment them out the code runs because they are not used (yet) in backtest.py

#def EMA(self, prices, period):
	#	x = numpy.asarray(prices)
	#	weights = None
	#	weights = numpy.exp(numpy.linspace(-1., 0., period))
	#	weights /= weights.sum()

	#	a = numpy.convolve(x, weights, mode='full')[:len(x)]
	#	a[:period] = a[period]

	#       return a

	#def MACD(self, prices, nslow=26, nfast=12):
	#	emaslow = self.EMA(prices, nslow)
	#	emafast = self.EMA(prices, nfast)

	#       return emaslow, emafast, emafast - emaslow

**Comment by bwentzloff** [comment]
Sorry about that. I'll get that fixed this weekend.
