### ISSUE TITLE
What is a numpy?

### ISSUE THREAD

**Issue by derpaherk** [bwentzloff/trading-bot#30]
So when I go to run bot.py, live.py or backtest.py they fail at import numpy in botindicators.py.. I'm assuming that I need to have a numpy.py, But Part 3 doesn't have a numpy.py. I can get Part 3 to run when I comment out "import numpy"  `#import numpy`.

This is what I get when "import numpy" is not commented out.
`c:\Trading-Bot>python bot.py
Traceback (most recent call last):
  File "bot.py", line 6, in <module>
    from botstrategy import BotStrategy
  File "c:\Trading-Bot\botstrategy.py", line 2, in <module>
    from botindicators import BotIndicators
  File "c:\Trading-Bot\botindicators.py", line 1, in <module>
    import numpy
ImportError: No module named numpy`

Here is what I get when I comment out "import numpy" - Side note I changed to USDT_BTC
`c:\Trading-Bot>python bot.py
Open: 11311.7737104 Close: None High: 11311.7737104 Low: 11311.7737104 Current: 11311.7737104
Open: 11311.7737104 Close: None High: 11324.6035649 Low: 11311.7737104 Current: 11324.6035649`

Is there supposed to be a numpy.py?  Also when can we expect to seen another Video/code release? I know there are other trading bots on GitHub, but I like how you are doing the guides on YouTube for your code. I'd like to stick with it.

**Comment by AlexanderBollbach** [comment]
numpy is a widely popular python package for scientific computing.
(basically doing lotsa of common math operations) . perhaps look into how
to link against python packages in general and pull it in yourself

**Comment by derpaherk** [comment]
Thank you for the information. I was able to install numpy by running this line.
`python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose`
I got it from https://scipy.org/install.html

I know it installed more than I needed.. But I can now take out the comment and numpy imports fine.
